# Generated by Django 4.1.7 on 2023-05-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shepherd',
            new_name='Speaker',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='shepherd',
            new_name='speaker',
        ),
    ]
