# Generated by Django 4.2.1 on 2023-06-05 06:28

import Member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_rename_shepherd_speaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=Member.models.upload_image_path),
        ),
        migrations.AddField(
            model_name='speaker',
            name='telephone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
