# Generated by Django 4.2.1 on 2023-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_speaker_picture_speaker_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
