# Generated by Django 4.2.1 on 2023-06-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_alter_speaker_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='telephone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
